feat(docs): Initial editor with `codemirror`
svelte-docgen/svelte-docgen pull request #66
Opened 2024-12-26 11:33 UTC by xeho91

Resolves #65

2024-12-30 15:35 UTC, xeho91 commented
@ciscorn I've added a feature to REPL where input will be encoded (and compressed) into page url search parameters.

It will be easier to make reproductions, I hope.

2024-12-31 04:40 UTC, ciscorn commented
> input will be encoded (and compressed) into page url search parameters.

@xeho91  I was also planning to implement this later. Nice work 👍 

You might already know this, but _GraphiQL_ has the same feature: https://graphql.github.io/swapi-graphql/

2025-01-01 05:28 UTC, xeho91 commented
@ciscorn For now, I did as much as I could to provide _a basic_ editor. With the ability to provide a reproduction link.

Stuff like autocomplete, diagnostics, VIM mode, etc. We can add later in the future. 

Next, I would like to focus on the output pane to make it more pleasing for the eye.

2025-01-01 08:32 UTC, ciscorn requested changes

2025-01-01 08:32 UTC, ciscorn commented on apps/docs/src/routes/playground/docgen.ts
> +		return Promise.resolve(prepare_docgen(fsmap)(source));
I noticed a significant slowdown and found that docgen is being re-initialized here every time parsing occurs.

In my demo implementation, prepareDocgen was called only once, and its result was reused throughout.

2025-01-01 08:32 UTC, ciscorn commented on apps/docs/src/routes/playground/docgen.ts
> +	const fsmap = await tsvfs.createDefaultMapFromCDN(COMPILER_OPTIONS, ts.version, false, ts, {
This should also be called only once and reused, even though it has some caching mechanism.

2025-01-01 08:32 UTC, ciscorn commented on apps/docs/src/routes/playground/docgen.ts
> +	}
This could also be moved to the preparing phase.

2025-01-01 08:44 UTC, ciscorn commented
I agree with moving forward without overengineering it!!

2025-01-01 08:47 UTC, ciscorn commented
BTW, I’m not a big fan of the "Blocks" of shadcn for documentation purposes. It feels more like a modern web app rather than proper documentation, and I feel it doesn’t align with the vibe of the Svelte community. Even in React’s shadcn/ui, the documentation adopts a more traditional layout.

That said, given the time constraints, the current style should be fine as is.

2025-01-01 09:36 UTC, xeho91 commented
> BTW, I’m not a big fan of the "Blocks" of shadcn for documentation purposes. It feels more like a modern web app rather than documentation, and I feel it doesn’t align with the vibe of the Svelte community. Even in React’s shadcn/ui, the documentation adopts a more traditional layout.
> 
> That said, given the time constraints, the current style should be fine as is.

I certainly plan to change the design in the future. At the moment, I need anything that will help me speed up the process to achieve goals for SvelteHack. If I'll manage to save some time before the deadline, then I'll try to work on it.

2025-01-01 09:37 UTC, xeho91 commented on apps/docs/src/routes/playground/docgen.ts
> +		return Promise.resolve(prepare_docgen(fsmap)(source));
Thanks! I've refactored it because I had problems understanding the flow. I think it works faster now. Could you re-check?

2025-01-01 15:01 UTC, ciscorn commented on apps/docs/src/routes/playground/docgen.ts
> +		return Promise.resolve(prepare_docgen(fsmap)(source));
Yes, feel free to refactor, as my implementation is merely a proof of concept!

2025-01-01 15:24 UTC, ciscorn commented on apps/docs/src/routes/playground/docgen.svelte.ts
> +	#fsmap = $state<SvelteMap<string, string>>(new SvelteMap());
q: Does #fsmap really need to be a 'state'? At the moment, it doesn’t seem to serve any purpose.

2025-01-01 15:24 UTC, ciscorn approved these changes

2025-01-01 15:26 UTC, ciscorn commented
I’m excited to see CodeMirror integrated!

2025-01-02 06:46 UTC, xeho91 commented on apps/docs/src/routes/playground/docgen.svelte.ts
> +	#fsmap = $state<SvelteMap<string, string>>(new SvelteMap());
No, you're right. I don't remember why exactly I did put in `$state()` in the first place. I think I had an idea to provide a more detailed output in the _loading_ phase.

But... that would be over-engineering and definitely **not** a priority right now. Thanks for spotting it!

2025-01-02 06:47 UTC, xeho91 commented on apps/docs/src/routes/playground/docgen.svelte.ts
> +				true,
@ciscorn Before merging, one last question. Was there any good reason why you didn't have `cache` _(from `createDefaultMapFromCDN)_ enabled at start?

2025-01-02 07:28 UTC, ciscorn commented on apps/docs/src/routes/playground/docgen.svelte.ts
> +				true,
Ah, sorry about that! I probably set it to `false` while testing whether `target: ESNext` was usable and forgot to switch it back. It should work perfectly fine with `true`.

2025-01-02 08:04 UTC, merged